# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTVibration',
    'RCTImage',
    # Add any other subspecs you want to use in your project
  ]

  #target 'AwesomeProjectTests' do
    #inherit! :search_paths
  #end

end
